################################################################
# 
# Project:  Elvin
# File:     $Source: /Users/d/work/elvin/CVS/web-org/cgi-bin/formats/Makefile,v $
#
################################################################
#
#  add more source files here
#
CGI_FILES  := freg.py fbrowse.py fshow.py
SUB_DIRS   := 
TARGET     := formats

################################################################
#  anything after here shouldn't need to be changed (much!)
################################################################

INCLUDE := ../..
include $(INCLUDE)/Makefile.config

$(GEN_FILES): Makefile \
	$(INCLUDE)/Makefile.config \
	$(INCLUDE)/org.m4

################################################################
