################################################################
# 
# Project:  Elvin
# File:     $Source: /Users/d/work/elvin/CVS/web-org/papers/Makefile,v $
#
################################################################
#
#  add more source files here
#
RAW_FILES :=
SRC_FILES := $(wildcard *.htmi)
SUB_DIRS  := \
	apchi98 \
	auug2k \
	auug97 \
	chi98 \
	ecscw99 \
	es99 \
	invicom01
TARGET    := papers

################################################################
#  anything after here shouldn't need to be changed (much!)
################################################################

INCLUDE := ..
include $(INCLUDE)/Makefile.config

$(GEN_FILES): Makefile \
	$(INCLUDE)/Makefile.config \
	$(INCLUDE)/org.m4

################################################################

