################################################################
# 
# Project:  Elvin
# File:     $Source: /Users/d/work/elvin/CVS/web-org/papers/invicom01/Makefile,v $
#
################################################################
#
#  add more source files here
#
RAW_FILES := $(wildcard *.pdf)
SRC_FILES :=
SUB_DIRS  :=
TARGET    := papers/invicom01

################################################################
#  anything after here shouldn't need to be changed (much!)
################################################################

INCLUDE := ../..
include $(INCLUDE)/Makefile.config

$(GEN_FILES): Makefile \
	$(INCLUDE)/Makefile.config \
	$(INCLUDE)/org.m4

################################################################

